# Generated by Django 3.2.9 on 2021-11-25 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password_room', models.CharField(blank=True, max_length=255, null=True)),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreateRoom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room create',
            },
        ),
        migrations.CreateModel(
            name='RoomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_joined', models.ManyToManyField(blank=True, related_name='Joined_Other_Rooms', to='chat.RoomCreate')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnteredRoom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room list',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname_msg', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Send_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message history',
                'ordering': ('date_added',),
            },
        ),
    ]
