# Generated by Django 3.2.9 on 2021-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password_room', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
